<a href="https://colab.research.google.com/github/RocioGO24/Python/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [4]:
# Import numpy as np and see the version

# your code here
pass
import numpy as np


In [5]:
# Create a 1D array of numbers from 0 to 9
# your code here
pass
lista=list(range(9))
print(lista)


[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [6]:
# Create random vector of size 10 and replace the maximum value by 0
pass
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)


[0.602035   0.17067977 0.77402853 0.12799875 0.         0.90286668
 0.95058734 0.21955942 0.96347834 0.10258268]


In [8]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
pass
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

8


In [9]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [10]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])

[4 5 6 7]


In [11]:
# Create a 3×3 numpy array of all True’s
# your code here
pass
tmp=10*np.random.random((4,4))
mascara=tmp>0
print(tmp)
print("-------------------")
print(mascara)

[[0.31444612 6.06847584 0.82433676 0.85957704]
 [8.5182498  8.25218129 0.31413409 5.48123607]
 [6.75116467 9.08946152 5.20575234 9.34414388]
 [1.68552778 8.23157682 5.33431316 1.11561092]]
-------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
# Extract all odd numbers from arr
# your code here
pass
tmp = np.random.randint(1, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = np.mod(tmp, 2) == 0
print(tmp[mask])

[[7 3 1 7]
 [3 3 1 8]
 [8 5 5 3]
 [1 9 4 8]]
----------------------------------
[8 8 4 8]


In [13]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
pass
tmp = np.arange(10,50)
print(tmp)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
# Reverse a vector (first element becomes last)
pass
vectorInvertido = tmp[::-1]
print(vectorInvertido)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [15]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
pass
tmp = np.random.randint(1, 101, size=(10, 10))
minimo = np.min(tmp)
maximo = np.max(tmp)
print("Matriz")
print(tmp)
print("Minimo")
print(minimo)
print("Maximo")
print(maximo)
pass

Matriz
[[ 81  30  96   1  13   7  32  75  83  33]
 [ 74   8  91  39   1   7 100   1  53  91]
 [ 15   1  29  87  65  10  33  40  52  69]
 [  7  49  42   5  40  77  96  96  91  55]
 [ 48  71  61  41  41  18  55  80  20  43]
 [ 31   7  95  22  74  56  93  57  59  13]
 [ 35  64 100  84  13  84  97  91  74  42]
 [ 29  78   1  91  81  72  11  68  84  32]
 [ 67  83  55  54  74  39  52  55  86  58]
 [ 51  30  94  83  28  45  20  41  30  58]]
Minimo
1
Maximo
100


In [16]:
# Create a 3x3x3 array with random values
pass
tmp2 = np.random.random((3,3,3))
print(tmp2)

[[[0.76309708 0.4740306  0.14147404]
  [0.30416249 0.05654472 0.15682126]
  [0.15355687 0.55432608 0.23831617]]

 [[0.84848486 0.29988876 0.48630797]
  [0.71806967 0.96175586 0.62602367]
  [0.2612052  0.38665893 0.30314855]]

 [[0.19971472 0.32710372 0.86575038]
  [0.14321016 0.93547644 0.04511107]
  [0.08368205 0.47563865 0.05814089]]]


In [17]:
# Replace all odd numbers in arr with -1
# your code here
pass
tmp = np.random.randint(1, 11, size=(3, 3, 3))
print(tmp)
print("-----------------")
tmp[tmp % 2 == 1] = -1
print(tmp)

[[[8 2 5]
  [2 8 6]
  [5 8 6]]

 [[5 1 7]
  [4 3 1]
  [3 6 4]]

 [[1 9 3]
  [3 4 1]
  [8 9 4]]]
-----------------
[[[ 8  2 -1]
  [ 2  8  6]
  [-1  8  6]]

 [[-1 -1 -1]
  [ 4 -1 -1]
  [-1  6  4]]

 [[-1 -1 -1]
  [-1  4 -1]
  [ 8 -1  4]]]


In [18]:
# Create an array of type float
pass
tmpF = np.random.rand(5)
print(tmpF)

[0.9527392  0.21165482 0.55529716 0.47602165 0.3263796 ]


In [19]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
pass
lista = list(range(12))
lista = np.array(lista)
two_d_array = lista.reshape(2, 6)
print(two_d_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [20]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
pass
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valoresComunes = np.intersect1d(Z1, Z2)
print(Z1)
print("-------------")
print(Z2)
print("-------------")
print(valoresComunes)

[9 6 3 2 3 0 8 4 8 1]
-------------
[3 2 0 1 5 8 3 7 7 1]
-------------
[0 1 2 3 8]


In [21]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

pass
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print('Array A')
print(A)
print('Array B')
print(B)

if np.array_equal(A,B):
  print('Son iguales')
else:
  print('Son diferentes')

Array A
[0 0 1 1 1]
Array B
[0 1 0 0 1]
Son diferentes


In [22]:
# Stack arrays a and b vertically
# your code here
pass
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaVertical = np.vstack((A, B))
print("Stacked Array:")
print(matrizApiladaVertical)

Array A
[0 0 1 1 1]
Array B
[0 1 0 0 1]
Stacked Array:
[[0 0 1 1 1]
 [0 1 0 0 1]]


In [23]:
# Stack the arrays a and b horizontally.
# your code here
pass
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaHorizontal = np.hstack((A, B))
print("Stacked Array:")
print(matrizApiladaHorizontal)

Array A
[0 0 1 1 1]
Array B
[0 1 0 0 1]
Stacked Array:
[0 0 1 1 1 0 1 0 0 1]


In [24]:
# Get all items between 5 and 10 from array tmp.
# your code here
# pass
import numpy as np
tmp = np.arange(15)
print(tmp)
print('-------------')
valores = tmp[(tmp>=5)&(tmp<=10)]
print(valores)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------
[ 5  6  7  8  9 10]


In [25]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
"""Arrays"""
# a = np.array([5, 7, 9, 8, 6, 4, 5])
a = np.random.randint(1,10,7)
print("Array A")
print(a)
# b = np.array([6, 3, 4, 8, 9, 7, 1])
b = np.random.randint(1,10,7)
print("Array B")
print(b)

print("----------------------------")

"""Method 1"""
print("Method 1")
def parMax(a, b):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(a, b)

c = parMax(a, b)
print(c)

print("----------------------------")

print("Method 2")
"""Method 2"""
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

c = np.array([maxx(x, y) for x, y in zip(a, b)])
print(c)

Array A
[8 9 4 4 4 8 1]
Array B
[8 4 7 8 8 3 1]
----------------------------
Method 1
[8 9 7 8 8 8 1]
----------------------------
Method 2
[8 9 7 8 8 8 1]


In [26]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

# your code here
pass
arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print("------------------------")
print("Cambio de columnas 1 y 2")
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------
Cambio de columnas 1 y 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [27]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)

[[8.50922046 8.79577921 5.3288033 ]
 [6.52293392 7.15307978 6.35627293]
 [8.78947482 6.38432061 5.51223247]
 [9.38080824 9.26178082 5.40734425]
 [9.78691853 9.11328526 6.79739328]]
