<a href="https://colab.research.google.com/github/RocioGO24/Python/blob/main/Nunpy_IAipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
a=np.random.randint(1,11,size=(3,4))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 5  1  6  8]
 [ 1  9 10  2]
 [10  9  6  8]]
[[ 6  9  6  1]
 [ 7  7  8  6]
 [ 4 10 10  6]]
(3, 4)
(3, 4)
adding numbers
[[11 10 12  9]
 [ 8 16 18  8]
 [14 19 16 14]]
substracting numbers
[[-1 -8  0  7]
 [-6  2  2 -4]
 [ 6 -1 -4  2]]
multiply numbers
[[30  9 36  8]
 [ 7 63 80 12]
 [40 90 60 48]]
[[11 10 12  9]
 [ 8 16 18  8]
 [14 19 16 14]]
[[30  9 36  8]
 [ 7 63 80 12]
 [40 90 60 48]]
[[0.83333333 0.11111111 1.         8.        ]
 [0.14285714 1.28571429 1.25       0.33333333]
 [2.5        0.9        0.6        1.33333333]]


In [40]:
a=np.random.randint(1,11,size=(2,3))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[8 2 5]
 [9 1 3]]
[[10  2  9  4]
 [ 9  1  1 10]
 [ 5  2  9  7]]
[[123  28 119  87]
 [114  25 109  67]]
[[123  28 119  87]
 [114  25 109  67]]


In [42]:
a=np.random.randint(1,11,size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[8 7]
 [7 7]]
[[8 7]
 [7 7]]


In [43]:
a=np.random.randint(1,11,size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('------------------')
print(c)

(4, 3)
(3,)
[[9 3 9]
 [6 8 5]
 [9 1 3]
 [7 6 7]]
[1 0 2]
(4, 3)
------------------
[[ 5  1  6]
 [ 8  1  9]
 [10  2 10]
 [ 9  6  8]]


In [44]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)
print('------------------')
c=a+b
print(c)

[[9 3 9]
 [6 8 5]
 [9 1 3]
 [7 6 7]]
[1 0 2]
[[10  3 11]
 [ 7  8  7]
 [10  1  5]
 [ 8  6  9]]
------------------
[[10  3 11]
 [ 7  8  7]
 [10  1  5]
 [ 8  6  9]]


In [45]:
a=np.array([1,2,3])


tmp=np.tile(a,(6,1))
print(tmp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
matrix1 = np.random.randint(0, 10, size=(6, 6))
print(matrix1)

aux=np.mean(matrix1)
print(aux)
print('------------------')
matrix2 = np.random.randint(0, 10, size=(6, 6))
print(matrix2)
print('------------------')
print("\nEl promedio por filas de la matriz es:")
print(promedio_por_filas)

[[3 7 8 7 2 3]
 [8 1 8 8 6 4]
 [1 6 3 8 4 9]
 [3 6 4 6 4 2]
 [4 9 4 0 2 5]
 [2 9 7 3 3 8]]
4.916666666666667
------------------
[[1 2 8 2 9 0]
 [6 7 2 6 3 6]
 [0 9 2 8 1 8]
 [4 3 4 1 7 4]
 [1 5 2 1 7 7]
 [6 7 8 3 6 3]]
------------------

El promedio por filas de la matriz es:
[6.         4.16666667 3.83333333 3.33333333 3.83333333 4.16666667]


In [47]:
matrix_X = np.array([[1, 2], [3, 4]])
matrix_Y = np.array([[5, 6], [7, 8]])
matrix_result = np.dot(matrix_X, matrix_Y)

array_A = np.array([1, 2, 3])
squared_array_A = np.square(array_A)

In [48]:
print(squared_array_A)

[1 4 9]


In [49]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])
result_broadcasting = array_2d + array_1d

print("Resultado del Broadcasting:")
print(result_broadcasting)

array_X = np.array([[1, 2], [3, 4]])
array_Y = np.array([[5, 6]])
concatenated_array = np.concatenate((array_X, array_Y.T), axis=1)

print("\nResultado de la Concatenación:")
print(concatenated_array)

Resultado del Broadcasting:
[[11 22 33]
 [14 25 36]]

Resultado de la Concatenación:
[[1 2 5]
 [3 4 6]]
